### PR TITLE
Bash to invoke API

### LINKED ISSUE #2: Shell script that authenticates against this API gateway using an AWS access key and secret key
Given now we have the dynamic secgroup, we also need a shell script that can generate the AWS v4 signature to authenticate against the API gateway.

@phuonghuynh could you help with this? Thanks!

### PR DESCRIPTION
**Pull request by phuonghuynh**
Fix #2

### CODE REVIEW

**Comment by phuonghuynh** [comment]
@ronaldtse Could we move this to new repo and open source, since google return nothing when finding any sample bash like this.

**Comment by ronaldtse** [comment]
Agree @phuonghuynh , I've created a new repo here for you: https://github.com/riboseinc/aws-authenticating-secgroup-scripts

Can you update the PR and move the appropriate scripts to the new repo, and then merge this? Thanks!

**Comment by phuonghuynh** [comment]
Yes @ronaldtse

**Comment by ronaldtse** [comment]
Thank you @phuonghuynh !

**Pull request merged**
